### ISSUE TITLE
Unable to find a way to cut the floors jpgs into tiles

### ISSUE THREAD

**Issue by helgso** [rhinorust/MoMa#17]
I was able to have Leaflet working (panning, zooming, changing floors) without the need to tile the floor jpgs into smaller pictures. However, this caused performance issues where my phone would get buggy in the furthest out zoom levels due to the size of the floor jpgs being displayed.

I therefore think the only way performance wise is to use tiles for our map. However, I haven't been able to find an algorithm or write one in C# that takes big jpgs and creates tiles for each zoom level compatible with Xamarin PCL.

**Comment by helgso** [comment]
I'm looking into replacing leaflet with our own implementation. HTML canvas works in HybridWebView which gives us access to drawImage() which can render selective parts of an image at a selective location. If this works we'd be able to use one jpg image while still tiling it, only rendering the part of the image that is visible on the screen

**Comment by helgso** [comment]
Renders too slowly. Guess we have to use precut tiles

**Comment by jonathanhamel4** [comment]
Okay so this is kind of an end point.. "You cannot write data's to asset/Raw folder, since it is packed(.apk) and not expandable in size." 
http://stackoverflow.com/questions/3760626/how-to-write-files-to-assets-folder-or-raw-folder-in-android#answer-9632452

**Comment by avinanda** [comment]
Fixed after choosing to stick with maptiler.
