### ISSUE TITLE
Lack of communication between C# and WebView

### ISSUE THREAD

**Issue by jonathanhamel4** [rhinorust/MoMa#5]
How to parse the JSON in JS? 
$.getJSON(), $.parseJSON(), JSON.parse(), etc. not working.

Where to store the JSON?

We should parse with C# and pass to JS.
http://stackoverflow.com/questions/11126242/using-jsonconvert-deserializeobject-to-deserialize-json-to-a-c-sharp-poco-class

How to use callJSFunction within HybridWebView? not accessible?
https://github.com/XLabs/Xamarin-Forms-Labs/wiki/HybridWebView

**Comment by RobRuff** [comment]
A possible solution explored is to parse the JSON with javascript and have the parsed object in the front end. 

Possible ways of implementing this solution are:
1) Using jQuery: http://www.pureexample.com/jquery/get-json.html
2) Using JSON.Net http://www.newtonsoft.com/json/help/html/Overload_Newtonsoft_Json_JsonConvert_DeserializeObject.htm

however reading files in javascript is not well documented, will do more research

**Comment by jonathanhamel4** [comment]
I have no problem if you wanna parse it with javascript HTTP protocol. JQuery, we would need jQuery mobile. We might wanna stay with javascript. Anyhow, I added a magnifier glass icon to the toolbaritem of map page. Although, I cant find a way to call a method of webview (js) from the content page (mapPage)..

If we want to go with javascript, we need to store the json into a js var in a seperate file like Justin mentioned on slack.

**Comment by jonathanhamel4** [comment]
Using the dependency service (with IJavascriptInterface) and WebView.LoadUrl of HybridWebViewRenderer, we are able to communicate from C# to JS. Although, we are not able to call an implemented fct in js. We have to write the fct in C# (the DOM is still accessible).
